language: node_js
node_js:
 - 8

addons:
 apt:
  packages:
   - sshpass

before_install:
 - echo "install nodejs"
 - nvm install 8
 - npm install yarn -g
 - node --version
 - npm --version
 - nvm --version

install:
 - yarn install

script:
 - yarn relay
 - yarn build
 - rm dist/index.js
 - rm dist/tv.xml
 - mv dist/index.html .
 - yarn cordova -- --storePassword=$STORE_PWD --password=$STORE_PWD
 - yarn info we-office-cli --json > we-office-cli.json
 - export LATEST=$(node -p "require('./we-office-cli.json').data['dist-tags'].latest")
 - export CURRENT=$(node -p "require('./packages/we-office-cli/package.json').version") 

after_success:
 - mv index.html dist

 - node -p "require('./package.json').version" > dist/app.apk.version
 - mv dist $APP_NAME
 - tar cvfz $APP_NAME.tgz $APP_NAME
 - ls $APP_NAME -l
 - travis_wait sshpass -e scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $APP_NAME.tgz "$DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH"
 - sshpass -e ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $DEPLOY_USER@$DEPLOY_HOST "tar xvfz $DEPLOY_PATH/$APP_NAME.tgz -C $DEPLOY_PATH && rm $DEPLOY_PATH/$APP_NAME.tgz"

before_deploy:
 - pwd
 - cd packages/we-office-cli

deploy:
 provider: npm
 email: "lalalic@139.com"
 api_key: $NPM_KEY
 skip_cleanup: true
 on:
  branch: master
  condition: "$LATEST != $CURRENT"