language: node_js
node_js:
 - 8

addons:
 apt:
  packages:
   - sshpass

before_install:
 - npm install yarn -g

install:
 - yarn install

script:
 - yarn relay
 - yarn build
 - rm dist/index.js
 - mv dist/index.html .
 - yarn info we-office-cli --json > we-office-cli.json
 - export LATEST=$(node -p "require('./we-office-cli.json').data['dist-tags'].latest")
 - export CURRENT=$(node -p "require('./packages/we-office-cli/package.json').version")

after_success:
 - mv index.html dist
#upload web pages
 - node -p "require('./package.json').version" > dist/app.apk.version
 - rm dist/config.xml
 - mv dist $APP_NAME
 - tar cvfz $APP_NAME.tgz $APP_NAME
 - ls $APP_NAME -l
 - travis_wait sshpass -e scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $APP_NAME.tgz "$DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH"
 - sshpass -e ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $DEPLOY_USER@$DEPLOY_HOST "tar xvfz $DEPLOY_PATH/$APP_NAME.tgz -C $DEPLOY_PATH && rm $DEPLOY_PATH/$APP_NAME.tgz"
#sync cloud code to qili2.com
 - yarn sync --service "$QILI" --token "$QILI_TOKEN" --appId "$QILI_APPID" --contact "$QILI_CONTACT"

#deploy cli
before_deploy:
 - pwd
 - cd packages/we-office-cli

deploy:
 provider: npm
 email: "lalalic@139.com"
 api_key: $NPM_KEY
 skip_cleanup: true
 on:
  branch: master
  condition: "$LATEST != $CURRENT"
